#!/bin/sh
set -e

if [ -f /var/lib/pwrstat-gui/settings.txt ]; then
    echo "Loading existing settings..."
    rm -f /usr/share/pwrstat-gui/data/settings.txt
    cp /var/lib/pwrstat-gui/settings.txt /usr/share/pwrstat-gui/data/
    rm -rf /var/lib/pwrstat-gui/
fi